FROM node:12.19.0-alpine as builder
LABEL maintainer="GeeksCAT<info@geekscat.org>"

# Install tini process manager to forward signals to node
RUN apk add --no-cache tini
ENTRYPOINT ["/sbin/tini", "--"]

COPY app /usr/src/app
WORKDIR /usr/src/app/
RUN yarn install

# Set environment variables
ENV NODE_ENV production
ENV NUXT_HOST 0.0.0.0
ENV NUXT_PORT 3000

RUN yarn build \
    && yarn cache clean

CMD [ "yarn", "start" ]
